lapd_pcap: fix illegal VLA within struct
Another weird and unique gcc supported extension, clang complains:
  CC       input/lapd_pcap.lo
input/lapd_pcap.c:134:8: error: fields must have a constant size:
'variable length array in structure' extension will never be supported
                char buf[msg->len];
                     ^

The kernel has been VLA-free since 2018, let's try not to make it worse.

Change-Id: I547d900ba88c60bae5b53345e1aee104bacd310d